const HOTELS = [
  {
    id_hosteleria: 1,
    nombre: "Cabaña Río Azul",
    precio_por_noche: 1450,
    direcciones: { ciudad: "Jalpan de Serra", estado: "Querétaro" },
    capacidad: 4,
    descripcion: "Cabaña rústica a orillas del río, ideal para desconectarte y disfrutar de la naturaleza.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop&q=60",
    estado: "activo",
  },
  {
    id_hosteleria: 2,
    nombre: "Cabaña Mirador del Cielo",
    precio_por_noche: 1850,
    direcciones: { ciudad: "Pinal de Amoles", estado: "Querétaro" },
    capacidad: 6,
    descripcion: "Vistas espectaculares a la Sierra Gorda con terraza panorámica y climatizada.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=60",
    estado: "activo",
  },
  {
    id_hosteleria: 3,
    nombre: "Hotel Boutique Hacienda La Loma",
    precio_por_noche: 2600,
    direcciones: { ciudad: "Jalpan de Serra", estado: "Querétaro" },
    capacidad: 8,
    descripcion: "Hotel boutique con piscina, restaurante regional y jacuzzi al aire libre.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=60",
    estado: "activo",
  },
  {
    id_hosteleria: 4,
    nombre: "Cabaña Los Ríos",
    precio_por_noche: 1200,
    direcciones: { ciudad: "Landa de Matamoros", estado: "Querétaro" },
    capacidad: 4,
    descripcion: "Frente a los manantiales, con fogata, hamacas y acceso directo al río.",
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&auto=format&fit=crop&q=60",
    estado: "activo",
  },
  {
    id_hosteleria: 5,
    nombre: "Cabaña del Valle Verde",
    precio_por_noche: 1080,
    direcciones: { ciudad: "Pinal de Amoles", estado: "Querétaro" },
    capacidad: 5,
    descripcion: "Confortable cabaña rodeada de bosque de pino y encino, perfecta para familias.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800&auto=format&fit=crop&q=60",
    estado: "activo",
  },
  {
    id_hosteleria: 6,
    nombre: "Villa Santa María",
    precio_por_noche: 1950,
    direcciones: { ciudad: "Arroyo Seco", estado: "Querétaro" },
    capacidad: 6,
    descripcion: "Amplia villa con jardín privado, cocina equipada y estacionamiento.",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=60",
    estado: "activo",
  },
];

const EXPERIENCES = [
  {
    id: 1,
    name: "Cascada Puente de Dios",
    price: 450,
    rating: 4.9,
    location: "Pinal de Amoles, Querétaro",
    imageSrc: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&auto=format&fit=crop&q=60",
    duration: 4,
    category: "Naturaleza",
    groupSize: 12,
  },
  {
    id: 2,
    name: "Senderismo al Mirador del Cielo",
    price: 550,
    rating: 4.8,
    location: "Pinal de Amoles, Querétaro",
    imageSrc: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=60",
    duration: 6,
    category: "Aventura",
    groupSize: 15,
  },
  {
    id: 3,
    name: "Tour por las Misiones Franciscanas",
    price: 800,
    rating: 4.9,
    location: "Jalpan de Serra, Querétaro",
    imageSrc: "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800&auto=format&fit=crop&q=60",
    duration: 8,
    category: "Cultura",
    groupSize: 10,
  },
  {
    id: 4,
    name: "Kayak en la Presa de Jalpan",
    price: 650,
    rating: 4.7,
    location: "Jalpan de Serra, Querétaro",
    imageSrc: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&auto=format&fit=crop&q=60",
    duration: 3,
    category: "Deportes acuáticos",
    groupSize: 8,
  },
  {
    id: 5,
    name: "Avistamiento de aves al amanecer",
    price: 400,
    rating: 4.8,
    location: "Arroyo Seco, Querétaro",
    imageSrc: "https://images.unsplash.com/photo-1518803194621-27188ba362c9?w=800&auto=format&fit=crop&q=60",
    duration: 3,
    category: "Naturaleza",
    groupSize: 12,
  },
  {
    id: 6,
    name: "Noche de campamento bajo las estrellas",
    price: 900,
    rating: 5.0,
    location: "Sierra Gorda, Querétaro",
    imageSrc: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&auto=format&fit=crop&q=60",
    duration: 12,
    category: "Aventura",
    groupSize: 20,
  },
];

export { HOTELS, EXPERIENCES };